contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8ffa88bd-3f69-4977-8db5-33893517cc38
inputs: []
name: Test Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bbee9248-f927-4c53-8a1e-47996509c4ac
      iscommand: false
      name: ""
      version: -1
    taskid: bbee9248-f927-4c53-8a1e-47996509c4ac
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 20,
          "y": -520
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      issueTypeName:
        simple: '[System] Incident'
      projectName:
        simple: cssoar
      summary:
        simple: this is a test ticket to test polling ${incident.starttime}
      using:
        simple: jira-v2_instance_srik
    separatecontext: false
    skipunavailable: false
    task:
      brand: jira-v2
      description: Creates a new issue in Jira.
      id: 4a0bfbe0-3a5b-4fa8-8f0e-70abdc5fd3ce
      iscommand: true
      name: Create Jira Ticket
      script: jira-v2|||jira-create-issue
      type: regular
      version: -1
    taskid: 4a0bfbe0-3a5b-4fa8-8f0e-70abdc5fd3ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 830,
          "y": 220
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 60
    note: false
    quietmode: 0
    scriptarguments:
      BUData:
        complex:
          accessor: BU}
          root: ${lists.BUList
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 66e5ae4d-a05d-4acd-8fac-178a0a662f85
      iscommand: false
      name: sub-pb
      playbookId: ba00221b-fb94-47aa-865a-5225c0ee2c63
      type: playbook
      version: -1
    taskid: 66e5ae4d-a05d-4acd-8fac-178a0a662f85
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -560,
          "y": 420
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      DstIP:
        complex:
          accessor: dest
          root: incident
      OnCall:
        simple: "false"
      Role:
        simple: Administrator
      SrcIP:
        complex:
          accessor: src
          root: incident
      Username:
        complex:
          accessor: srcuser
          root: incident
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 177a8496-d1e3-48ab-8eb3-2cf90fe884b5
      iscommand: false
      name: Hi
      playbookId: access_investigation_-_generic
      type: playbook
      version: -1
    taskid: 177a8496-d1e3-48ab-8eb3-2cf90fe884b5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -530,
          "y": 270
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: "Hi \n\nTest email"
      cc: null
      format: html
      methods:
      - email
      replyOptions:
      - "Yes"
      - "No"
      subject:
        simple: Test SOAR Ask
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: Analyst
    nexttasks:
      '#default#':
      - "7"
      "Yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5d96bf04-4e89-4f95-8880-a518f9febabf
      iscommand: false
      name: test the ask task
      type: condition
      version: -1
    taskid: 5d96bf04-4e89-4f95-8880-a518f9febabf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 270
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "Yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 08cd6a85-5787-4599-842b-98bc0242bf1d
      iscommand: false
      name: "Yes"
      script: Print
      type: regular
      version: -1
    taskid: 08cd6a85-5787-4599-842b-98bc0242bf1d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -150,
          "y": 480
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 81e06369-5fad-42de-8949-710e8a28f671
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 81e06369-5fad-42de-8949-710e8a28f671
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 130,
          "y": 630
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IPData=.={"city":val.city}
      ip:
        simple: 1.4.5.6
      using:
        simple: ipinfo_v2_instance_1
    separatecontext: false
    skipunavailable: false
    task:
      brand: ipinfo_v2
      description: Check IP reputation (when information is available, returns a JSON
        with details). Uses all configured Threat Intelligence feeds.
      id: c3c3b40d-82a9-41ff-8afe-8ab7df26af29
      iscommand: true
      name: Untitled Task
      script: ipinfo_v2|||ip
      type: regular
      version: -1
    taskid: c3c3b40d-82a9-41ff-8afe-8ab7df26af29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 810,
          "y": -30
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            value:
              simple: ${test.5.stop}
          operator: isTrue
          right:
            value: {}
      exitCondition: ""
      iscommand: false
      max: 6
      wait: 30
    note: false
    quietmode: 0
    scriptarguments:
      max_tries:
        simple: "6"
      taskid:
        simple: "5"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a531d26b-5505-48be-8595-085fad4b2ebf
      iscommand: false
      name: Test-SubplaybookCounter
      playbookId: 0b38269c-1a8e-403b-88aa-65e9fcd19ef9
      type: playbook
      version: -1
    taskid: a531d26b-5505-48be-8595-085fad4b2ebf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 20,
          "y": -200
        }
      }
  "10":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: res
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: ""
      title: fdfdf
      totalanswers: 0
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: sdsdf
      timings:
        completeafterreplies: 0
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: Administrator
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1ed07210-fac9-4003-8121-c5cac8f1f0f2
      iscommand: false
      name: Untitled Task
      type: collection
      version: -1
    taskid: 1ed07210-fac9-4003-8121-c5cac8f1f0f2
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": -190,
          "y": 125
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 514edfa0-9d1f-4cd1-86e0-afe6ca70c985
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 514edfa0-9d1f-4cd1-86e0-afe6ca70c985
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": -390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1215,
        "width": 1770,
        "x": -560,
        "y": -520
      }
    }
  }
